name: Add to mkoertgen Roadmap board

on:
  issues:
    types: [labeled]

jobs:
  add-to-project:
    if: github.event.label.name == 'tracked'
    runs-on: ubuntu-latest
    steps:
      - name: Add to mkoertgen Roadmap
        env:
          GH_TOKEN: ${{ secrets.ADD_TO_PROJECT_PAT }}
        run: gh project item-add 2 --owner mkoertgen --url ${{ github.event.issue.html_url }}
